server:
    port: 8081

spring:
    datasource:
        url: jdbc:mysql://localhost:3308/aluraflix
        username: root
        password: helloworld
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            