server:
    port: 8081

spring:
    data:
        web:
            pageable:
                default-page-size: 5
    datasource:
        url: jdbc:mysql://localhost:3308/aluraflix
        username: root
        password: helloworld
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        open-in-view: false
        show-sql: false
        defer-datasource-initialization: true
    sql:
        init:
            mode: always
    mustache:  
        check-template-location: false
    